# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotsecenv" do
  name "dotsecenv"
  desc "Safe environment secrets — encrypted at rest, ready to commit, easy to share."
  homepage "https://dotsecenv.com"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotsecenv"
  manpage "man/man1/dotsecenv.1"
  manpage "man/man1/dotsecenv-completion.1"
  manpage "man/man1/dotsecenv-init.1"
  manpage "man/man1/dotsecenv-init-config.1"
  manpage "man/man1/dotsecenv-init-vault.1"
  manpage "man/man1/dotsecenv-login.1"
  manpage "man/man1/dotsecenv-secret.1"
  manpage "man/man1/dotsecenv-secret-get.1"
  manpage "man/man1/dotsecenv-secret-put.1"
  manpage "man/man1/dotsecenv-secret-revoke.1"
  manpage "man/man1/dotsecenv-secret-share.1"
  manpage "man/man1/dotsecenv-validate.1"
  manpage "man/man1/dotsecenv-vault.1"
  manpage "man/man1/dotsecenv-vault-describe.1"
  manpage "man/man1/dotsecenv-vault-doctor.1"
  manpage "man/man1/dotsecenv-version.1"
  bash_completion "completions/dotsecenv.bash"
  zsh_completion "completions/dotsecenv.zsh"
  fish_completion "completions/dotsecenv.fish"
  depends_on formula: [
      "gnupg",
    ]

  on_macos do
    on_intel do
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
      sha256 "55492896cb3431468e1612bfbe5bb07446b2a4102c1ca1009621520337d29605"
    end
    on_arm do
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
      sha256 "0db88e724ab3491d0bdcf01e86d205f76c6ba7b64edb04e1b536f7736fa5b7f7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
      sha256 "ef82bd572891606129d0c7b8165cad8adcf392d2ae170a93580b9664f1fb1e1b"
    end
    on_arm do
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
      sha256 "6490f615efbb1c0b670a210409b1afe80be7ce649d1461125726d1047969737c"
    end
  end

  caveats do
    "For bash completions, install bash-completion:"
    "  brew install bash-completion@2"
    ""
    "To enable a shell plugin (automatic .env/.secenv loading), see:"
    "  https://github.com/dotsecenv/plugin"
  end

  # No zap stanza required
end
