# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotsecenv" do
  name "dotsecenv"
  desc "Safe environment secrets."
  homepage "https://dotsecenv.com"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotsecenv"
  manpage "man/man1/*.1"
  bash_completion "completions/dotsecenv.bash"
  zsh_completion "completions/dotsecenv.zsh"
  fish_completion "completions/myapp.fish"
  depends_on formula: [
      "gnupg",
    ]

  on_macos do
    on_intel do
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
      sha256 "ae909f1c0514d3d21181f64b230d2e9c260ced7a54ced6ce4f97dd29ce1af969"
    end
    on_arm do
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
      sha256 "66209acd68213f83ff619ea8e4f502b3d0bb04a14a4166ac534f4e72c4fe7d11"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
      sha256 "e267a15572f2c1f28c11bd02777278f0a83b910a8ab6a5a64fbdba29f4dea404"
    end
    on_arm do
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
      sha256 "1b6d477e7ae66f4fa7235054c6f05be6d3425badfd4b3108d7e3d3d025ffd3ad"
    end
  end

  postflight do
    system "#{bin}/dotsecenv", "--help"
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dotsecenv"]
    end
  end

  caveats do
    "For bash completions, install bash-completion:"
    "  brew install bash-completion@2"
  end

  # No zap stanza required
end
