# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotsecenv" do
  version "0.0.0-rc1"

  on_macos do
    on_intel do
      sha256 "75fbc1d6646b839f4e737925ac72e47cc96e4c6589a8bb8147c28b5204918b19"
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
    end
    on_arm do
      sha256 "25c0a13a57043b8520c37c95d2580711ef859884eecbc797d905743d4b87cc4b"
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
    end
  end

  on_linux do
    on_intel do
      sha256 "f18773ac2a6957450f5f4440b728df55b0fcf38d076f331f7da79c1d29e49b58"
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
    end
    on_arm do
      sha256 "25c0a13a57043b8520c37c95d2580711ef859884eecbc797d905743d4b87cc4b"
      url "https://github.com/dotsecenv/dotsecenv/releases/download/v#{version}/dotsecenv_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/dotsecenv/dotsecenv/"
    end
  end

  name "dotsecenv"
  desc "Safe environment secrets — encrypted at rest, ready to commit, easy to share."
  homepage "https://dotsecenv.com"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gnupg",
    ]

  binary "dotsecenv"
  manpage "man/man1/dotsecenv-completion.1"
  manpage "man/man1/dotsecenv-init-config.1"
  manpage "man/man1/dotsecenv-init-vault.1"
  manpage "man/man1/dotsecenv-init.1"
  manpage "man/man1/dotsecenv-login.1"
  manpage "man/man1/dotsecenv-secret-get.1"
  manpage "man/man1/dotsecenv-secret-revoke.1"
  manpage "man/man1/dotsecenv-secret-share.1"
  manpage "man/man1/dotsecenv-secret-store.1"
  manpage "man/man1/dotsecenv-secret.1"
  manpage "man/man1/dotsecenv-validate.1"
  manpage "man/man1/dotsecenv-vault-describe.1"
  manpage "man/man1/dotsecenv-vault-doctor.1"
  manpage "man/man1/dotsecenv-vault.1"
  manpage "man/man1/dotsecenv-version.1"
  manpage "man/man1/dotsecenv.1"
  bash_completion "completions/dotsecenv.bash"
  fish_completion "completions/dotsecenv.fish"
  zsh_completion "completions/dotsecenv.zsh"

  # No zap stanza required

  caveats <<~EOS
    For bash completions, install bash-completion:
      brew install bash-completion@2

    To enable a shell plugin (automatic .env/.secenv loading), see:
      https://github.com/dotsecenv/plugin
  EOS
end
